name: Testing github workflows

on: push

jobs:
  init:
    runs-on: ubuntu-latest

    env:
      STEP1 : "le code vient d'etre pousse sur github"
    steps:
      - run: echo 'bonsoir Heredia! Comment tu vas?'
             echo "step1 = $STEP1"
             echo " salut mon code est ${{secrets.TAIST}}"
      - run: echo $HOSTNAME
             echo"salut = ${{vars.STEP2}}"
             echo"step 3= ${{vars.HEREDIA}}"
             
